// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package db

import (
	"database/sql"
	"time"
)

type Admin struct {
	ID        int64          `json:"id"`
	Fullname  string         `json:"fullname"`
	Email     string         `json:"email"`
	Role      sql.NullString `json:"role"`
	LoggedIn  sql.NullTime   `json:"logged_in"`
	LoggedOut sql.NullTime   `json:"logged_out"`
	Password  string         `json:"password"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type Adminlog struct {
	ID        int64        `json:"id"`
	AdminID   int64        `json:"admin_id"`
	LoggedIn  time.Time    `json:"logged_in"`
	LoggedOut sql.NullTime `json:"logged_out"`
	CreatedAt time.Time    `json:"created_at"`
}

type Employee struct {
	ID        int64        `json:"id"`
	Fullname  string       `json:"fullname"`
	Email     string       `json:"email"`
	Mobile    string       `json:"mobile"`
	Password  string       `json:"password"`
	Token     string       `json:"token"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Signedvisitor struct {
	ID        int64         `json:"id"`
	VisitorID int64         `json:"visitor_id"`
	SignedIn  time.Time     `json:"signed_in"`
	SignedOut sql.NullTime  `json:"signed_out"`
	VisitID   sql.NullInt64 `json:"visit_id"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}

type Visit struct {
	ID         int64         `json:"id"`
	Status     string        `json:"status"`
	Reason     string        `json:"reason"`
	EmployeeID sql.NullInt64 `json:"employee_id"`
	VisitorID  int64         `json:"visitor_id"`
	CreatedAt  time.Time     `json:"created_at"`
	UpdatedAt  sql.NullTime  `json:"updated_at"`
}

type Visitor struct {
	ID          int64         `json:"id"`
	Fullname    string        `json:"fullname"`
	Email       string        `json:"email"`
	Mobile      string        `json:"mobile"`
	CompanyName string        `json:"company_name"`
	Picture     string        `json:"picture"`
	SignIn      time.Time     `json:"sign_in"`
	SignOut     sql.NullTime  `json:"sign_out"`
	EmployeeID  sql.NullInt64 `json:"employee_id"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
}
